version: "3.7"

services:

  bot-trade-binance:
    container_name: bot-trade-binance
    build: .
    env_file:
      - .env-${APP_ENV}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - "./src:/src"
    networks:
      - default
      - nmb

networks:
  default:
    name: nmb
    driver: bridge
  nmb:
    external: true
